# Generated by Django 5.1.3 on 2025-03-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='current_location_lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='current_location_lng',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='dropoff_location_lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='dropoff_location_lng',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='pickup_location_lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='pickup_location_lng',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='trip',
            name='current_cycle_used',
            field=models.FloatField(default=0),
        ),
    ]
